### ISSUE TITLE
Project requirements 

### ISSUE THREAD

**Issue by chrisji** [HLT-ISTI/QuaNet#1]
Hi @aesuli, @AlexMoreo - please could you include the requirements (with versions) for this project

**Comment by chrisji** [comment]
Also, I believe there is a package/module missing from the project:

```python
from feature_selection.round_robin import RoundRobin
ModuleNotFoundError: No module named 'feature_selection'
```

**Comment by AlexMoreo** [comment]
I have removed the import (it was from another project). Now it should work!
