### ISSUE TITLE
SVMperf custom loss

### ISSUE THREAD

**Issue by chrisji** [HLT-ISTI/QuaNet#2]
Hi there,

I'm aiming to reproduce the results of the QuaNet paper, but believe you depend on some custom loss functions that are not in the base SVMperf implementation (KLD, NKLD, etc)

Are able to include the SVMperf modifications to this repo for reproducibility?

Best wishes,
Chris

**Comment by aesuli** [comment]
I've added to the repo [the patch that implements the quantification-oriented loss functions](https://github.com/HLT-ISTI/QuaNet/blob/cikm/svm-perf-quantification.patch)

**Comment by chrisji** [comment]
Many thanks for the patch - looks like this still omits `nkld`, and `q` losses however

For reproducibility, I believe mappings for `13` and `22` will need to exist in SVMperf as given in `baselines.py`
```python 
# losses with their respective codes in svm_perf implementation
valid_losses = {'01': 0, 'kld': 12, 'nkld': 13, 'q': 22,  ...
```

Do you have a patch that includes these?

**Comment by aesuli** [comment]
Right, it was an old version. I've updated it to include all the tested methods.
